### PR TITLE
change example from 'is' assignment to 'put/into' assignment

### PR DESCRIPTION
**Pull request by marcinruszkiewicz**
As discovered in #127:

There's the example that says `My world is nothing without your love`, but that should be a poetic number literal or an error, so the result at best would be `my world = 7744`, not `my world = 0 - your love`. 

This PR replaces the example with the `Put nothing without your love into my world`, so that it's clear what it does, it's valid syntax, and it doesn't confuse people further.

I'm not sure if we should clarify in the poetic section somewhere that `A soul is nothing without your love` is just invalid and doesn't mean anything since it has a Literal Keyword but extra words.

### CODE REVIEW

**Comment by young-steveo** [comment]
I don't think the spec is wrong here.  I interpret `My world is nothing without your love` as equivalent to `my world = 0 - your love`.  The section on [Poetic Type Literals](https://github.com/dylanbeattie/rockstar#poetic-type-literals) has examples like:

```
Tommy is nobody
```

The way I've implemented this in Thrash:  if the first word after `is` is recognized as a reserved keyword or a literal word, it's not a poetic number.

I also feel that this allows for better arrangement of lyrics, since I don't want to be "Putting x into y" for assignment in every single rockstar program.

**Comment by cwfitzgerald** [comment]
This is really just the debate in #112 all over again. I think we should leave the poetic literals be as they are described in #117, don't allow arbitrary sub-expressions on the right hand side of a poetic type literal.

**Comment by marcinruszkiewicz** [comment]
@young-steveo " if the first word after is is recognized as a reserved keyword or a literal word, it's not a poetic number" yes, but it's also not a poetic type literal, since that says "s a single line consisting of a variable name, the is keyword and the required value literal". 

Only `nothing` on its own is a value literal.

Maybe it should be fixed with another poetic statement alltogether, so it's clear that `is` + a single keyword is a Type, `is/was/were` + more words is a Number, and, I don't know, `Tommy thinks nothing without your love` is assigning an expression? Because I do agree it looks much much better than `Put nothing without your love into Tommy` :)

**Comment by marcinruszkiewicz** [comment]
@cwfitzgerald You can pull this one into #134 maybe? Limiting the number of pull requests would be probably nice and this would serve as an additional example

**Comment by cwfitzgerald** [comment]
Sure thing, I'll see if I can get around to it tomorrow.

**Comment by cwfitzgerald** [comment]
@marcinruszkiewicz Alright I've gotten myself a little turned around. What do I need to add to #134 from this PR?

**Comment by dylanbeattie** [comment]
Moved discussion into https://github.com/dylanbeattie/rockstar/issues/158

**Pull request closed without merging**
