### PR TITLE
Add Kaiser-Ruby to implementation list

### PR DESCRIPTION
**Pull request by marcinruszkiewicz**
This is an implementation of a Rockstar to Ruby transpiler, which is obviously named Kaiser-Ruby, because what else could I name a thing like that.

It's currently a work in progress, however most of the language features are already implemented and the two examples in my repository (FizzBuzz from this readme and Fibonacci generator from one of the issues here) are working, can be transpiled into Ruby code, and executed correctly.

Also what is worth mentioning, due to Ruby being really Unicode friendly, it handles Metal Umlauts #83 both in values and in variable names, because why not. Also now has a REPL #119, because again, why not.

### CODE REVIEW

**Comment by gunnerwolf** [comment]
Admittedly I'm not personally a huge fan of Ruby, but I have to admire the name here. Took me seeing "kaizer-ruby" to realise what you were referencing :+1:

**Comment by cwfitzgerald** [comment]
As a cultural idiot, could someone explain?

**Comment by Spaceghost** [comment]
This is a really awesome addition to the soirée of implementations!

**Comment by gunnerwolf** [comment]
@cwfitzgerald [Kaiser Chiefs](https://en.wikipedia.org/wiki/Kaiser_Chiefs) are a rock band from Leeds, UK, most famous for their song [Ruby](https://en.wikipedia.org/wiki/Ruby_(Kaiser_Chiefs_song))

**Comment by marcinruszkiewicz** [comment]
Exactly that. It's pretty common for Ruby developers to give fancy names to their gems (we have Rails, but also Paperclip, Sinatra, Jenkins and so on, for a few examples), so I've figured it can't hurt to do the same :)

**Comment by gunnerwolf** [comment]
In a similar vein, we have `maiden` named after *iron* maiden, because it's written in *rust*, and `thrash`, as in *thrash metal*, because it's written in Go and designed to be fast

**Comment by cwfitzgerald** [comment]
God I am bad at naming things....

**Comment by marcinruszkiewicz** [comment]
I'm not sure if editing the original PR makes a notification (I suspect not), so this comment is just a notice that the implementation is finally working and can run FizzBuzz.

```
$ kaiser-ruby execute ./examples/fizzbuzz.rock 
1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz

$ 
```

**Pull request merged**
