### PR TITLE
Add Wording Clearing Up Variable Scope

### LINKED ISSUE #111: Variable scope
There's nothing in the current spec detailing scope for variables, although it seems to indicate they're mostly pure functions i.e. no setting of global variables except at top-level; only change to the outer scope's variables is the function's return value.

### PR DESCRIPTION
**Pull request by cwfitzgerald**
Resolves #111.

### CODE REVIEW

**Comment by cwfitzgerald** [comment]
Sure! Hmm. I was going to say that should not compile, but following that logic this shouldn't compile either because FunctionB isn't defined:

```
FunctionA takes X
Give back FunctionB taking X

FunctionB takes X
Give back X times X
```

We then end up with C/C++'s declaration problem, which is frankly a little stupid, especially in this context. I don't know what to do about this.

**Comment by cwfitzgerald** [comment]
I was thinking about allowing functions to be treated as any standard variable, allowing nested functions among other things (higher order functions). This is in stark contrast with the C/C++ function model, where functions/globals are symbols and the way you pass them around is with pointers to their addresses. 

Some questions to ponder:
- Are functions just variables to function objects? If so, can you overwrite them with a different function?
- Do these bindings happen at compile time or at run time? Compile time would make the compilers stronger (as they can generate better code).
- Should functions be special cases to this rule and have a "linking" step in compilation where function calls are pointed to their callees?

**Comment by Suloch** [comment]
@cwfitzgerald It is meaningful that I answer these question with respect to how they are implemented in chirp?

**Comment by cwfitzgerald** [comment]
@Suloch Sure. The two main things I'm thinking debating about is the ease of implementation, and the ease of programming. My concerns mainly come from my attempt at building an optimizing compiler, so I'm trying to avoid features that pessimize the output code.

**Comment by Suloch** [comment]
These are answer to the above question.
- Yes, functions are just variables to function objects. But, they can't be overwritten with other function or literal.

- As it is an interpreter, there is no linking step, functions are referenced like any other variables(that is looking up the symbol table). 

***
`FunctionA takes X`
`Give back FunctionB taking X`

`FunctionB takes X`
`Give back X times X`
This code would run as intended in chirp as it does not execute any statement while the function is being defined. So it will not look for FunctionB while defining FunctionA, it will just assume that it exists.
And when FunctionA is called it will run normally as both FunctionA and FunctionB exists in the symbol table as object type variables.
With linking functions during compile time, we would not be able to use this feature directly.

**Pull request merged**
